# Generated by Django 3.1 on 2020-08-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('ticker', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('shares', models.IntegerField()),
                ('avg_buy_price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('booked_profit', models.DecimalField(decimal_places=3, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('transaction_type', models.CharField(choices=[('B', 'BUY'), ('S', 'SELL')], default='B', max_length=1)),
                ('traded_time', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.security')),
            ],
        ),
    ]
