# Generated by Django 3.1 on 2020-08-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200804_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolio.security'),
        ),
    ]
